// Please place this file in DDLStudies/src/components/

#include "GaudiKernel/DeclareFactoryEntries.h"

#include "../CBMCCheck.h"
#include "../CosmicData.h"
#include "../CosmicsSignal.h"
#include "../DataVR.h"
#include "../DESDEff.h"
#include "../DiLepCutFlow.h"
#include "../DispElec.h"
#include "../HNL.h"
#include "../Kshort_DDL.h"// This was added  for Kshort_DDL
#include "../LepReco.h"
#include "../LifetimeFit.h"
#include "../LRTImpact.h"
#include "../LowMassAOD.h"
#include "../MultiTrackDV.h"
#include "../MuonMatch.h"
#include "../PromptBkg.h"
#include "../SignalDESD.h"
#include "../SignalStudy.h"
#include "../SMBkg.h"
#include "../TrigEff.h"
#include "../VertexReco.h"

DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, CBMCCheck)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, CosmicData)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, CosmicsSignal)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, DataVR)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, DESDEff)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, DiLepCutFlow)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, DispElec)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, LepReco)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, LifetimeFit)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, LRTImpact)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, SignalDESD)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, SignalStudy)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, SMBkg)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, TrigEff)

#ifndef XAOD_ANALYSIS
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, LowMassAOD)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, MultiTrackDV)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, MuonMatch)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, PromptBkg)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, VertexReco)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, HNL)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(DDL, Kshort_DDL) // This was added  for Kshort_DDL


#endif

DECLARE_FACTORY_ENTRIES(DDLStudies)
{
  DECLARE_NAMESPACE_ALGORITHM(DDL, CBMCCheck);
  DECLARE_NAMESPACE_ALGORITHM(DDL, CosmicData);
  DECLARE_NAMESPACE_ALGORITHM(DDL, CosmicsSignal);
  DECLARE_NAMESPACE_ALGORITHM(DDL, DataVR);
  DECLARE_NAMESPACE_ALGORITHM(DDL, DESDEff);
  DECLARE_NAMESPACE_ALGORITHM(DDL, DiLepCutFlow);
  DECLARE_NAMESPACE_ALGORITHM(DDL, DispElec);
  DECLARE_NAMESPACE_ALGORITHM(DDL, LepReco);
  DECLARE_NAMESPACE_ALGORITHM(DDL, LifetimeFit);
  DECLARE_NAMESPACE_ALGORITHM(DDL, LRTImpact);
  DECLARE_NAMESPACE_ALGORITHM(DDL, SignalDESD);
  DECLARE_NAMESPACE_ALGORITHM(DDL, SignalStudy);
  DECLARE_NAMESPACE_ALGORITHM(DDL, SMBkg);
  DECLARE_NAMESPACE_ALGORITHM(DDL, TrigEff);

  #ifndef XAOD_ANALYSIS
  DECLARE_NAMESPACE_ALGORITHM(DDL, LowMassAOD);
  DECLARE_NAMESPACE_ALGORITHM(DDL, MultiTrackDV);
  DECLARE_NAMESPACE_ALGORITHM(DDL, MuonMatch);
  DECLARE_NAMESPACE_ALGORITHM(DDL, PromptBkg);
  DECLARE_NAMESPACE_ALGORITHM(DDL, VertexReco);
  DECLARE_NAMESPACE_ALGORITHM(DDL, HNL);
  DECLARE_NAMESPACE_ALGORITHM(DDL, Kshort_DDL);// This was added  for Kshort_DDL

  #endif
}
